import { shoes1, shoes2, shoes3, shoes4, shoes5, shoes6, shoes7, shoes8, shoes9, shoes10, shoes11, shoes12, shoes13, shoes14, shoes15, shoes16, shoes17, shoes18, shoes19, shoes20, shoes21, shoes22, shoes23, shoes24, shoes25, shoes26, shoes27, shoes28, shoes29, shoes30 } from './assests/shoes/importShoes';

import { cloth1, cloth2, cloth3, cloth4, cloth5, cloth6, cloth7, cloth8, cloth9, cloth10, cloth11, cloth12, cloth13, cloth14, cloth15, cloth16, cloth17, cloth18, cloth19, cloth20, cloth21, cloth22, cloth23, cloth24, cloth25, cloth26, cloth27, cloth28, cloth29, cloth30, cloth31, cloth32, cloth33, cloth34, cloth35, cloth36, cloth37, cloth38, cloth39, cloth40 } from './assests/clothes/importClothes';

import { gear1, gear2, gear3, gear4, gear5, gear6, gear7, gear8, gear9, gear10, gear11, gear12, gear13, gear14, gear15, gear16, gear17, gear18, gear19, gear20, gear21, gear22, gear23, gear24, gear25, gear26, gear27, gear28, gear29, gear30 } from './assests/gears/importGears';

export const PRODUCTS = [
    {
        id: 1,
        productName: "Nike Air Force 1'07",
        price: 7495.0,
        productImage: shoes1,
        category: "shoes",
    },
    {
        id: 2,
        productName: "Nike Vomero 5",
        price: 14995.0,
        productImage: shoes2,
        category: "shoes",
    },
    {
        id: 3,
        productName: "Nike Zoom Vomero 5",
        price: 14995.0,
        productImage: shoes3,
        category: "shoes",
    },
    {
        id: 4,
        productName: "Nike Air Max 90",
        price: 9995.0,
        productImage: shoes4,
        category: "shoes",
    },
    {
        id: 5,
        productName: "Nike Air Max Pulse",
        price: 13995,
        productImage: shoes5,
        category: "shoes",
    },
    {
        id: 6,
        productName: "Nike Air Max 97",
        price: 16695.0,
        productImage: shoes6,
        category: "shoes",
    },
    {
        id: 7,
        productName: "Nike Jordan Max Aura 5",
        price: 11895.0,
        productImage: shoes7,
        category: "shoes",
    },
    {
        id: 8,
        productName: "Nike Air Max 270",
        price: 14995.0,
        productImage: shoes8,
        category: "shoes",
    },
    {
        id: 9,
        productName: "Nike E-Series AD",
        price: 6295.0,
        productImage: shoes9,
        category: "shoes",
    },
    {
        id: 10,
        productName: "Nike Air Max AD",
        price: 8295.0,
        productImage: shoes10,
        category: "shoes",
    },
    {
        id: 11,
        productName: "Nike  Air Max Solo",
        price: 8695.0,
        productImage: shoes11,
        category: "shoes",
    },
    {
        id: 12,
        productName: "Nike Air Max Pulse III",
        price: 17495.0,
        productImage: shoes12,
        category: "shoes",
    },
    {
        id: 13,
        productName: "Nike Air Jordan Legacy 312 Low",
        price: 12995.0,
        productImage: shoes13,
        category: "shoes",
    },
    {
        id: 14,
        productName: "Nike Jumpman MVP",
        price: 15295.0,
        productImage: shoes14,
        category: "shoes",
    },
    {
        id: 15,
        productName: "Nike Air Max SC Leather",
        price: 6795.0,
        productImage: shoes15,
        category: "shoes",
    },
    {
        id: 16,
        productName: "Nike Air Max 1",
        price: 12795.0,
        productImage: shoes16,
        category: "shoes",
    },
    {
        id: 17,
        productName: "Nike Dunk High Retro",
        price: 8827.0,
        productImage: shoes17,
        category: "shoes",
    },
    {
        id: 18,
        productName: "Nike Air Jordan 1 Retro High OG",
        price: 16147.0,
        productImage: shoes18,
        category: "shoes",
    },
    {
        id: 19,
        productName: "Nike Air Jordan 1 Low",
        price: 8995.0,
        productImage: shoes19,
        category: "shoes",
    },
    {
        id: 20,
        productName: "Nike Air Force 1'07",
        price: 9695.0,
        productImage: shoes20,
        category: "shoes",
    },
    {
        id: 21,
        productName: "Nike Dunk Low Retro",
        price: 8695.0,
        productImage: shoes21,
        category: "shoes",
    },
    {
        id: 22,
        productName: "Nike Fly.By Mid 3",
        price: 4995.0,
        productImage: shoes22,
        category: "shoes",
    },
    {
        id: 23,
        productName: "Nike Elevate 3",
        price: 7095.0,
        productImage: shoes23,
        category: "shoes",
    },
    {
        id: 24,
        productName: "Nike Court Legacy Next Nature",
        price: 4995.0,
        productImage: shoes24,
        category: "shoes",
    },
    {
        id: 25,
        productName: "Nike SB Dunk Low Pro Premium",
        price: 9207.0,
        productImage: shoes25,
        category: "shoes",
    },
    {
        id: 26,
        productName: "Nike Air Force 1 Low Billie",
        price: 11895.0,
        productImage: shoes26,
        category: "shoes",
    },
    {
        id: 27,
        productName: "Nike Waffle Debut",
        price: 6295.0,
        productImage: shoes27,
        category: "shoes",
    },
    {
        id: 28,
        productName: "Nike Air Vapor Max 2023 Feyknit",
        price: 19295.0,
        productImage: shoes28,
        category: "shoes",
    },
    {
        id: 29,
        productName: "Nike Dunk High Retro",
        price: 9777.0,
        productImage: shoes29,
        category: "shoes",
    },
    {
        id: 30,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: shoes30,
        category: "shoes",
    },
    {
        id: 31,
        productName: "Jordan Dri FIT Sport",
        price: 3495.0,
        productImage: cloth1,
        category: "clothing",
    },
    {
        id: 32,
        productName: "Jordan Essentials Shorts",
        price: 2695.0,
        productImage: cloth2,
        category: "clothing",
    },
    {
        id: 33,
        productName: "Jordan Flight MVP Sweatshirt",
        price: 3895.0,
        productImage: cloth3,
        category: "clothing",
    },
    {
        id: 34,
        productName: "Jordan Flight MVP",
        price: 1995.0,
        productImage: cloth4,
        category: "clothing",
    },

    {
        id: 35,
        productName: "Jordan Essentials Trousers",
        price: 5995.0,
        productImage: cloth5,
        category: "clothing",
    },
    {
        id: 36,
        productName: "Paris Saint-Germain Hoddie",
        price: 4095.0,
        productImage: cloth6,
        category: "clothing",
    },
    {
        id: 37,
        productName: "Nike Dri-FIT Primary",
        price: 275.0,
        productImage: cloth7,
        category: "clothing",
    },
    {
        id: 38,
        productName: "Nike Air T-Shirt",
        price: 1795.0,
        productImage: cloth8,
        category: "clothing",
    },
    {
        id: 39,
        productName: "Paris Saint-Germain T-Shirt",
        price: 2295.0,
        productImage: cloth9,
        category: "clothing",
    },
    {
        id: 40,
        productName: "Paris Saint-Germain Shorts",
        price: 2495.0,
        productImage: cloth10,
        category: "clothing",
    },
    {
        id: 41,
        productName: "LeBron T-Shirt",
        price: 2695.0,
        productImage: cloth11,
        category: "clothing",
    },
    {
        id: 42,
        productName: "Nike Club Fleece Alumini Shorts",
        price: 3295.0,
        productImage: cloth12,
        category: "clothing",
    },
    {
        id: 43,
        productName: "Jordan Dri FIT Sport Shorts",
        price: 2295.0,
        productImage: cloth13,
        category: "clothing",
    },
    {
        id: 44,
        productName: "Nike ISIA Long-Sleeves Top",
        price: 4995.0,
        productImage: cloth14,
        category: "clothing",
    },
    {
        id: 45,
        productName: "Paris Saint-Germain Trousers",
        price: 3995.0,
        productImage: cloth15,
        category: "clothing",
    },
    {
        id: 46,
        productName: "Nike ESC 1/2 Zip Wool Top",
        price: 17995.0,
        productImage: cloth16,
        category: "clothing",
    },
    {
        id: 47,
        productName: "Nike ESC Woven Shirt",
        price: 17995.0,
        productImage: cloth17,
        category: "clothing",
    },
    {
        id: 48,
        productName: "Nike ESC Woven Cargo Trousers",
        price: 16995.0,
        productImage: cloth18,
        category: "clothing",
    },
    {
        id: 49,
        productName: "Nike ESC Full Zip Wool Jumper",
        price: 19995.0,
        productImage: cloth19,
        category: "clothing",
    },
    {
        id: 50,
        productName: "Nike SB Skate T-Shirt",
        price: 2495.0,
        productImage: cloth20,
        category: "clothing",
    },
    {
        id: 51,
        productName: "Nike Dri-FIT UV Hyverse Sleeve Top",
        price: 1995.0,
        productImage: cloth21,
        category: "clothing",
    },
    {
        id: 52,
        productName: "Nike Dri-FIT Form Shorts",
        price: 2395.0,
        productImage: cloth22,
        category: "clothing",
    },
    {
        id: 53,
        productName: "Nike Sportswear Premium Essentials",
        price: 2695.0,
        productImage: cloth23,
        category: "clothing",
    },
    {
        id: 54,
        productName: "Nike ACG T-Shirt",
        price: 2895.0,
        productImage: cloth24,
        category: "clothing",
    },
    {
        id: 55,
        productName: "Jordan Oversized T-Shirt",
        price: 2595.0,
        productImage: cloth25,
        category: "clothing",
    },
    {
        id: 56,
        productName: "Jordan Essentails Top",
        price: 3495.0,
        productImage: cloth26,
        category: "clothing",
    },
    {
        id: 57,
        productName: "Jordan Flight Essentials T-Shirt",
        price: 2295.0,
        productImage: cloth27,
        category: "clothing",
    },
    {
        id: 58,
        productName: "Jordan Essentials Loopback Fleecee Trousers",
        price: 3795.0,
        productImage: cloth28,
        category: "clothing",
    },
    {
        id: 59,
        productName: "Jordan Essentials Oversized Graphic T-Shirt",
        price: 2657.0,
        productImage: cloth29,
        category: "clothing",
    },
    {
        id: 60,
        productName: "Jordan Flight Fleece Trousers",
        price: 4295.0,
        productImage: cloth30,
        category: "clothing",
    },
    {
        id: 61,
        productName: "Nike Dri-Fit Studio'72 Trousers",
        price: 3795.0,
        productImage: cloth31,
        category: "clothing",
    },
    {
        id: 62,
        productName: "Nike Sportswear Tech Fleece Windrunner Hoodie",
        price: 8995.0,
        productImage: cloth32,
        category: "clothing",
    },
    {
        id: 63,
        productName: "Nike Solo Smoosh Terry Crew",
        price: 4177.0,
        productImage: cloth33,
        category: "clothing",
    },
    {
        id: 64,
        productName: "Nike Pro Dri-Fit Long Sleeve Top",
        price: 1795.0,
        productImage: cloth34,
        category: "clothing",
    },
    {
        id: 65,
        productName: "Nike Sportswear Trend Fleece Crew",
        price: 5697.0,
        productImage: cloth35,
        category: "clothing",
    },
    {
        id: 66,
        productName: "Jordan Essentials Pullover Hoddie",
        price: 4095.0,
        productImage: cloth36,
        category: "clothing",
    },
    {
        id: 67,
        productName: "Nike ISPA Trousers 2.0",
        price: 10995.0,
        productImage: cloth37,
        category: "clothing",
    },
    {
        id: 68,
        productName: "Nike Miler Running Top",
        price: 1995.0,
        productImage: cloth38,
        category: "clothing",
    },
    {
        id: 69,
        productName: "Nike Sportswear Trend Short-Sleeve Top",
        price: 3995.0,
        productImage: cloth39,
        category: "clothing",
    },
    {
        id: 70,
        productName: "Jordan Sports Jam Warm-up Trousers",
        price: 4995.0,
        productImage: cloth40,
        category: "clothing",
    },
    {
        id: 71,
        productName: "Nike Dri-FIT Fly Swoosh Cap",
        price: 1295.0,
        productImage: gear1,
        category: "gear",
    },
    {
        id: 72,
        productName: "Nike Utility Shoe Tote",
        price: 1395.0,
        productImage: gear2,
        category: "gear",
    },
    {
        id: 73,
        productName: "Nike Storm-FIT ADV Utility Power",
        price: 4495.0,
        productImage: gear3,
        category: "gear",
    },
    {
        id: 74,
        productName: "Nike Premium Hip Pack",
        price: 2795.0,
        productImage: gear4,
        category: "gear",
    },
    {
        id: 75,
        productName: "Nike Air Max Gross Body Bag",
        price: 4077.0,
        productImage: gear5,
        category: "gear",
    },
    {
        id: 76,
        productName: "Jordan Rise Cap",
        price: 1195.0,
        productImage: gear6,
        category: "gear",
    },
    {
        id: 77,
        productName: "Nike Sportsswear Essentials",
        price: 3495.0,
        productImage: gear7,
        category: "gear",
    },
    {
        id: 78,
        productName: "Nike Heritage Hip Pack",
        price: 1895.0,
        productImage: gear8,
        category: "gear",
    },
    {
        id: 79,
        productName: "Jordan Flight MVP Pro Cap",
        price: 1995.0,
        productImage: gear9,
        category: "gear",
    },
    {
        id: 80,
        productName: "Nike Storm-FIT ADV Utility Speed",
        price: 7295.0,
        productImage: gear10,
        category: "gear",
    },
    {
        id: 81,
        productName: "Nike Premium Cross-Body Bag",
        price: 2295.0,
        productImage: gear11,
        category: "gear",
    },
    {
        id: 82,
        productName: "Nike Heritage Cross-Body Bag",
        price: 1395.0,
        productImage: gear12,
        category: "gear",
    },
    {
        id: 83,
        productName: "Nike Brasilia 9.5",
        price: 2495.0,
        productImage: gear13,
        category: "gear",
    },
    {
        id: 84,
        productName: "Nike Dri-FIT Club Cap",
        price: 1295.0,
        productImage: gear14,
        category: "gear",
    },
    {
        id: 85,
        productName: "Nike Shoe Box Bag",
        price: 2295.0,
        productImage: gear15,
        category: "gear",
    },
    {
        id: 86,
        productName: "Nike Brasilia 9.5 Training Backpack",
        price: 3495.0,
        productImage: gear16,
        category: "gear",
    },
    {
        id: 87,
        productName: "Nike Dri-FIT Club Featherlight Cap",
        price: 1595.0,
        productImage: gear17,
        category: "gear",
    },
    {
        id: 88,
        productName: "Nike Utility Speed Backpack",
        price: 4495.0,
        productImage: gear18,
        category: "gear",
    },
    {
        id: 89,
        productName: "Nike Dri-FIT ADV Club Cap",
        price: 1595.0,
        productImage: gear19,
        category: "gear",
    },
    {
        id: 90,
        productName: "Nike Heritage Backpack",
        price: 1995.0,
        productImage: gear20,
        category: "gear",
    },
    {
        id: 91,
        productName: "Jordan Pro Cap",
        price: 1695.0,
        productImage: gear21,
        category: "gear",
    },
    {
        id: 92,
        productName: "Nike Sportswear Esseentials Bag",
        price: 1895.0,
        productImage: gear22,
        category: "gear",
    },
    {
        id: 93,
        productName: "Nike Hoops Elite Bag",
        price: 1595.0,
        productImage: gear23,
        category: "gear",
    },
    {
        id: 94,
        productName: "Nike Brasilia 9.5 Duffle Bag",
        price: 2795.0,
        productImage: gear24,
        category: "gear",
    },
    {
        id: 95,
        productName: "Nike Storm-FIT ADV Apex Bucket Hat",
        price: 2295.0,
        productImage: gear25,
        category: "gear",
    },
    {
        id: 96,
        productName: "Nike Sportswear Essential Cross Body Bag",
        price: 1895.0,
        productImage: gear26,
        category: "gear",
    },
    {
        id: 97,
        productName: "Nike Brasilia Shoe Bag",
        price: 995.0,
        productImage: gear27,
        category: "gear",
    },
    {
        id: 98,
        productName: "Nike Heritage Waist Pack",
        price: 1395.0,
        productImage: gear28,
        category: "gear",
    },
    {
        id: 99,
        productName: "Nike Heritage Cross-Body Bag",
        price: 1895.0,
        productImage: gear29,
        category: "gear",
    },
    {
        id: 100,
        productName: "Nike Utility Power Backpack",
        price: 4995.0,
        productImage: gear30,
        category: "gear",
    }
]