import { shoes1, shoes2, shoes3, shoes4, shoes5, shoes6, shoes7, shoes8, shoes9, shoes10, shoes11, shoes12, shoes13, shoes14, shoes15, shoes16, shoes17, shoes18, shoes19, shoes20, shoes21, shoes22, shoes23, shoes24, shoes25, shoes26, shoes27, shoes28, shoes29, shoes30 } from './assests/shoes/importShoes';

import { cloth1, cloth2, cloth3, cloth4, cloth5, cloth6, cloth7, cloth8, cloth9, cloth10, cloth11, cloth12, cloth13, cloth14, cloth15, cloth16, cloth17, cloth18, cloth19, cloth20, cloth21, cloth22, cloth23, cloth24, cloth25, cloth26, cloth27, cloth28, cloth29, cloth30, cloth31, cloth32, cloth33, cloth34, cloth35, cloth36, cloth37, cloth38, cloth39, cloth40 } from './assests/clothes/importClothes';

export const PRODUCTS = [
    {
        id: 1,
        productName: "Nike Air Force 1'07",
        price: 7495.0,
        productImage: shoes1,
        category : "shoes",
    },
    {
        id: 2,
        productName: "Nike Vomero 5",
        price: 14995.0,
        productImage: shoes2,
        category: "shoes",
    },
    {
        id: 3,
        productName: "Nike Zoom Vomero 5",
        price: 14995.0,
        productImage: shoes3,
        category: "shoes",
    },
    {
        id: 4,
        productName: "Nike Air Max 90",
        price: 9995.0,
        productImage: shoes4,
        category: "shoes",
    },
    {
        id: 5,
        productName: "Nike Air Max Pulse",
        price: 13995,
        productImage: shoes5,
        category: "shoes",
    },
    {
        id: 6,
        productName: "Nike Air Max 97",
        price: 16695.0,
        productImage: shoes6,
        category: "shoes",
    },
    {
        id: 7,
        productName: "Nike Jordan Max Aura 5",
        price: 11895.0,
        productImage: shoes7,
        category: "shoes",
    },
    {
        id: 8,
        productName: "Nike Air Max 270",
        price: 14995.0,
        productImage: shoes8,
        category: "shoes",
    },
    {
        id: 9,
        productName: "Nike E-Series AD",
        price: 6295.0,
        productImage: shoes9,
        category: "shoes",
    },
    {
        id: 10,
        productName: "Nike Air Max AD",
        price: 8295.0,
        productImage: shoes10,
        category: "shoes",
    },
    {
        id: 11,
        productName: "Nike  Air Max Solo",
        price: 8695.0,
        productImage: shoes11,
        category: "shoes",
    },
    {
        id: 12,
        productName: "Nike Air Max Pulse III",
        price: 17495.0,
        productImage: shoes12,
        category: "shoes",
    },
    {
        id: 13,
        productName: "Nike Air Jordan Legacy 312 Low",
        price: 12995.0,
        productImage: shoes13,
        category: "shoes",
    },
    {
        id: 14,
        productName: "Nike Jumpman MVP",
        price: 15295.0,
        productImage: shoes14,
        category: "shoes",
    },
    {
        id: 15,
        productName: "Nike Air Max SC Leather",
        price: 6795.0,
        productImage: shoes15,
        category: "shoes",
    },
    {
        id: 16,
        productName: "Nike Air Max 1",
        price: 12795.0,
        productImage: shoes16,
        category: "shoes",
    },
    {
        id: 17,
        productName: "Nike Dunk High Retro",
        price: 8827.0,
        productImage: shoes17,
        category: "shoes",
    },
    {
        id: 18,
        productName: "Nike Air Jordan 1 Retro High OG",
        price: 16147.0,
        productImage: shoes18,
        category: "shoes",
    },
    {
        id: 19,
        productName: "Nike Air Jordan 1 Low",
        price: 8995.0,
        productImage: shoes19,
        category: "shoes",
    },
    {
        id: 20,
        productName: "Nike Air Force 1'07",
        price: 9695.0,
        productImage: shoes20,
        category: "shoes",
    },
    {
        id: 21,
        productName: "Nike Dunk Low Retro",
        price: 8695.0,
        productImage: shoes21,
        category: "shoes",
    },
    {
        id: 22,
        productName: "Nike Fly.By Mid 3",
        price: 4995.0,
        productImage: shoes22,
        category: "shoes",
    },
    {
        id: 23,
        productName: "Nike Elevate 3",
        price: 7095.0,
        productImage: shoes23,
        category: "shoes",
    },
    {
        id: 24,
        productName: "Nike Court Legacy Next Nature",
        price: 4995.0,
        productImage: shoes24,
        category: "shoes",
    },
    {
        id: 25,
        productName: "Nike SB Dunk Low Pro Premium",
        price: 9207.0,
        productImage: shoes25,
        category: "shoes",
    },
    {
        id: 26,
        productName: "Nike Air Force 1 Low Billie",
        price: 11895.0,
        productImage: shoes26,
        category: "shoes",
    },
    {
        id: 27,
        productName: "Nike Waffle Debut",
        price: 6295.0,
        productImage: shoes27,
        category: "shoes",
    },
    {
        id: 28,
        productName: "Nike Air Vapor Max 2023 Feyknit",
        price: 19295.0,
        productImage: shoes28,
        category: "shoes",
    },
    {
        id: 29,
        productName: "Nike Dunk High Retro",
        price: 9777.0,
        productImage: shoes29,
        category: "shoes",
    },
    {
        id: 30,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: shoes30,
        category: "shoes",
    },
    {
        id: 31,
        productName: "Jordan Dri FIT Sport",
        price : 3495.0,
        productImage: cloth1,
        category: "clothing",
    },
    {
        id: 32,
        productName: "Jordan Essentials Shorts",
        price: 2695.0,
        productImage: cloth2,
        category: "clothing",
    },
    {
        id: 33,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth3,
        category: "clothing",
    },
    {
        id: 34,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth4,
        category: "clothing",
    },

    {
        id: 35,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth5,
        category: "clothing",
    },
    {
        id: 36,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth6,
        category: "clothing",
    },
    {
        id: 37,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth7,
        category: "clothing",
    },
    {
        id: 38,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth8,
        category: "clothing",
    },
    {
        id: 39,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth9,
        category: "clothing",
    },
    {
        id: 40,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth10,
        category: "clothing",
    },
    {
        id: 41,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth11,
        category: "clothing",
    },
    {
        id: 42,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth12,
        category: "clothing",
    },
    {
        id: 43,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth13,
        category: "clothing",
    },
    {
        id: 44,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth14,
        category: "clothing",
    },
    {
        id: 45,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth15,
        category: "clothing",
    },
    {
        id: 46,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth16,
        category: "clothing",
    },
    {
        id: 47,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth17,
        category: "clothing",
    },
    {
        id: 48,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth18,
        category: "clothing",
    },
    {
        id: 49,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth19,
        category: "clothing",
    },
    {
        id: 50,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth20,
        category: "clothing",
    },
{
        id: 51,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
    productImage: cloth21,
        category: "clothing",
    },
    {
        id: 52,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth22,
        category: "clothing",
    },
    {
        id: 53,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth23,
        category: "clothing",
    },
{
        id: 54,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
    productImage: cloth24,
        category: "clothing",
    },
    {
        id: 55,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth25,
        category: "clothing",
    },
{
        id: 56,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
    productImage: cloth26,
        category: "clothing",
    },
    {
        id: 57,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth27,
        category: "clothing",
    },
    {
        id: 58,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth28,
        category: "clothing",
    },
{
        id: 59,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
    productImage: cloth29,
        category: "clothing",
    },
    {
        id: 60,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth30,
        category: "clothing",
    },
{
        id: 61,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
    productImage: cloth31,
        category: "clothing",
    },
    {
        id: 62,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth32,
        category: "clothing",
    },
{
        id: 63,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
    productImage: cloth33,
        category: "clothing",
    },
    {
        id: 64,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth34,
        category: "clothing",
    },
{
        id: 65,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
    productImage: cloth35,
        category: "clothing",
    },
    {
        id: 66,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth36,
        category: "clothing",
    },
    {
        id: 67,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth37,
        category: "clothing",
    },
    {
        id: 68,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth38,
        category: "clothing",
    },
    {
        id: 69,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth39,
        category: "clothing",
    },
    {
        id: 70,
        productName: "Nike Air Force 1'07 LV8",
        price: 10795.0,
        productImage: cloth40,
        category: "clothing",
    },
// {
//         id: 71,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 72,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
// {
//         id: 73,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 74,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
// {
//         id: 75,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 76,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 77,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 78,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
// {
//         id: 79,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 80,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 81,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 82,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 83,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
// {
//         id: 84,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 85,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 86,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
// {
//         id: 87,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 88,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 89,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
// {
//         id: 90,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 91,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
// {
//         id: 92,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 93,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 94,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 95,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 96,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 97,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 98,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 99,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
//     {
//         id: 100,
//         productName: "Nike Air Force 1'07 LV8",
//         price: 10795.0,
//         productImage: cloth1,
//         category: "clothing",
//     },
]